experiment:
  name: chat_sentry_training
  run_name: hatebert_multhead

mlflow:
  tracking_uri: http://<MLFLOW_IP>:5000

data:
  train_path: /workspace/data/processed/train.csv
  val_path: /workspace/data/processed/val.csv
  test_path: /workspace/data/processed/test.csv
  max_length: 128

model:
  type: transformer
  encoder_name: GroNLP/hateBERT
  dropout: 0.1

training:
  batch_size: 16
  epochs: 3
  lr: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  num_workers: 2
  weighted_bce: false

evaluation:
  threshold_tuning: false

output:
  dir: /workspace/outputs/hatebert_multhead